# https://golangci-lint.run/usage/configuration
version: "2"

run:
  timeout: 5m
  tests: true
  concurrency: 4

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gocyclo
    - gosec
    - misspell
    - revive
    - interfacebloat
    - iface
    - gocritic
    - bodyclose
    - makezero
    - lll

  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    gocyclo:
      min-complexity: 15
    interfacebloat:
      max: 5
    iface:
      enable:
        - opaque
        - identical
    lll:
      line-length: 120
      tab-width: 1
    revive:
      rules:
        - name: blank-imports
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
