codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%        # Hard threshold - fail if below 70%
        threshold: 1%      # Allow 1% drop from target
        if_not_found: failure
    patch:
      default:
        target: 70%        # New code must have 70% coverage
        threshold: 1%
        if_not_found: success

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
