codecov:
  require_ci_to_pass: yes
  strict_yaml_branch: feat/code_cov_pipeline_addition  # Force Codecov to use YAML from this branch

coverage:
  precision: 2
  round: down
  range: "75...100"
  
  status:
    # Ensure status checks are enabled
    changes: false  # Don't require changes to run status checks
    project:
      default:
        target: "75%"        # Target coverage - fail if below 75%
        threshold: "0%"      # No drop allowed - strict enforcement
        if_not_found: failure
        removed_code_behavior: off  # Don't ignore removed code
    patch:
      default:
        target: "75%"        # New code must have at least 75% coverage  
        threshold: "0%"      # No drop allowed - strict enforcement
        if_not_found: failure
        removed_code_behavior: off  # Don't ignore removed code

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
