codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "75...100"

  status:
    project:
      default:
        target: 75%
        threshold: 1%
        if_not_found: success
    patch:
      default:
        target: 75%
        threshold: 1%
        if_not_found: success

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false