codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "75...100"

  status:
    project:
      default:
        target: 75%        # Target coverage - fail if below 74% (75% - 1%)
        threshold: 1%      # Allow 1% drop from target before failing
        if_not_found: failure
    patch:
      default:
        target: 75%        # New code must have at least 74% coverage
        threshold: 1%      # Allow 1% drop from target before failing
        if_not_found: success

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
