name: Assign

on:
  issues:
    types: [opened, reopened]
  pull_request_target:
    types: [opened, reopened]

jobs:
  assign:
    runs-on:
      - self-hosted
      - non-api
      - X64
    steps:
      - uses: actions/github-script@v6
        with:
          # Please add your name to assignees
          script: |
            github.rest.issues.addAssignees({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              assignees: ['KarthikBoddeda', 'stuckinforloop', 'alok87']
            })